import { StyleSheet } from 'react-native';

import { ACCENT } from '@/constants/controls';

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-start',
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  modalOverlayPressable: {
    flex: 1,
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '88%',
    width: '100%',
    direction: 'rtl',
    writingDirection: 'rtl',

  },
  dragHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#ddd',
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  stepHeader: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#eee',
    gap: 8,
  },
  stepHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  jumpToLastButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: 'white',
    flexShrink: 0,
  },
  jumpToLastButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: ACCENT,
  },
  titleWithStep: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#11181C',
  },
  stepIndicator: {
    fontSize: 14,
    fontWeight: '600',
    color: ACCENT,
  },
  stepLabel: {
    fontSize: 13,
    color: '#888',
    fontWeight: '500',
    writingDirection: 'rtl',
  },
  stepScroll: {
    flexGrow: 0,
  },
  stepScrollContent: {
    paddingBottom: 8,
  },
  stepBody: {
    padding: 24,
    gap: 20,
    writingDirection: 'rtl',
  },
  fieldGroup: {
    gap: 8,
    alignItems: 'flex-start',
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#555',
    writingDirection: 'rtl',

  },
  emptyHint: {
    fontSize: 14,
    color: '#aaa',
    fontStyle: 'italic',
    writingDirection: 'rtl',
    alignSelf: 'stretch',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 16,
    color: '#11181C',
    textAlign: 'right',
    alignSelf: 'stretch',
  },
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-start',
    alignSelf: 'stretch',
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fafafa',
  },
  chipWide: {
    flexGrow: 1,
    alignItems: 'center',
  },
  chipSelected: {
    backgroundColor: ACCENT,
    borderColor: ACCENT,
  },
  chipText: {
    fontSize: 14,
    color: '#444',
    fontWeight: '500',
    textAlign: 'right',
  },
  chipTextSelected: {
    color: '#fff',
  },
  programList: {
    gap: 8,
    marginTop: 4,
  },
  programRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#eee',
    backgroundColor: 'white',
  },
  programRowSelected: {
    borderColor: ACCENT,
    backgroundColor: 'rgba(255,106,6,0.10)',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#ccc',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: ACCENT,
    borderColor: ACCENT,
  },
  programInfo: {
    flex: 1,
    gap: 2,
  },
  programRowName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#11181C',
    writingDirection: 'rtl',
  },
  programRowMeta: {
    fontSize: 12,
    color: '#888',
    writingDirection: 'rtl',
  },
  footer: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 24,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#eee',
  },
  backButton: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ddd',
    alignItems: 'center',
  },
  backButtonText: {
    fontSize: 16,
    color: '#666',
    fontWeight: '500',
  },
  nextButton: {
    flex: 2,
    flexDirection: 'row',
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: ACCENT,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  nextButtonCompact: {
    flex: 1,
  },
  nextButtonDisabled: {
    opacity: 0.4,
  },
  nextButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  deleteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginHorizontal: 24,
    marginTop: 10,
    paddingVertical: 13,
    borderRadius: 12,
    backgroundColor: '#e53935',
  },
  deleteButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
});
